# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
   - repo: self
   

variables:
  tag: '$(Build.BuildId)'
  imagerepository: 'kpds/repo4sir6cob'

stages:
- stage: Build
  displayName: Build ,Push and Run
  jobs:
  - job: Build
    displayName: Build ,Push and Run
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build Docker Image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: '$(imageRepository):$(tag)'
      name: BuildImage
    - script: |
       echo "Imagename: $(imageRepository):$(tag)"
       docker images
      displayName: Printing Image Name and list of Docker Images
    
    - task: Docker@2
      displayName: Login to Docker Hub and Tag
      inputs:
       command: login
       containerRegistry: 'KPDockerConnection'
    - script: |
       echo "##vso[task.setvariable variable=imageId]$(docker inspect --format='{{.Id}}' $(docker images -q $(imageRepository):$(tag)))"
      displayName: Getting Image Id
    - script: |
       docker tag $imageId $(imageRepository):$(tag)
  
    - task: Docker@2
      displayName: Push Docker Image
      inputs:
        command: push
        containerRegistry: 'KPDockerConnection'
        repository: '$(imageRepository)'
        tags: '$(tag)'
      
    - task: DockerCompose@0
      displayName: Run Docker Image
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'KPDockerConnection'
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Run services'