# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
   - repo: self
   

variables:
  tag: '$(Build.BuildId)'
  imagerepository: 'kpds/repo4sir6cob'

stages:
- stage: Build
  displayName: Build ,Push and Run
  jobs:
  - job: Build
    displayName: Build ,Push and Run
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build Docker Image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: '$(imageRepository):$(tag)'
      name: BuildImage
    - script: |
       echo "Imagename: $(imageRepository):$(tag)"
       docker images
      displayName: Printing Image Name and list of Docker Images
    
    - task: Docker@2
      displayName: Login to Docker Hub and Tag
      inputs:
       command: login
       containerRegistry: 'KPDockerConnection'
    - script: |
       imageId=$(docker images --format "{{.ID}}" $(imageRepository):$(tag))
       echo "##vso[task.setvariable variable=imageId;isOutput=true]$imageId"
       echo "ImageId: $imageId"
      name: SetImageId
      displayName: Getting Image Id
    - script: |
       docker tag $[dependencies.BuildImage.outputs['BuildImage.imageId']] $(imageRepository):$(tag)
      displayName: Do Tag
  
    - task: Docker@2
      displayName: Push Docker Image
      inputs:
        command: push
        containerRegistry: 'KPDockerConnection'
        repository: '$(imageRepository)'
        tags: '$(tag)'
      
    - task: DockerCompose@0
      displayName: Run Docker Image
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'KPDockerConnection'
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Run services'
    - script: |
       echo "ImageId: $[dependencies.SetImageId.outputs['SetImageId.imageId']]"
      displayName: Printing ImageId