# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
   - repo: self
   

variables:
  tag: '$(Build.BuildId)'
  imagerepository: 'kpds/repo4sir6cob'

stages:
- stage: Build
  displayName: Build ,Push and Run
  jobs:
  - job: Build
    displayName: Build ,Push and Run
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build Docker Image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: '$(imageRepository):$(tag)'
    - task: Docker@2
      displayName: Push Docker Image
      inputs:
        command: push
        containerRegistry: 'KPDockerConnection'
        repository: '$(imageRepository)'
        tags: '$(tag)'
      
    - task: DockerCompose@0
      displayName: Run Docker Image
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'KPDockerConnection'
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Run services'