# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
 containers:
   - container: dockerRegistry
     image: kpds85/repo4sir6cob:getting-started
     endpoint: KPDockerConnection
   

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build and push
      inputs:
        command: buildAndPush
        containerRegistry: |
            kpds85/repo4sir6cob:getting-started
            kpds85
            Sivasan@5084
        repository: repo4sir6cob
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'KPDockerConnection'
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Run services'