# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
   - repo: self
   
variables:
  tag: '$(Build.BuildId)'
  imagerepository: 'kpds85/repo4sir6cob'

stages:
- stage: Build
  displayName: Build ,Push and Run
  jobs:
  - job: Build
    displayName: Build ,Push and Run
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: |
              docker build --file "$(Build.SourcesDirectory)/Dockerfile" --tag "$(imageRepository):$(tag)" --iidfile imageid.txt "$(Build.SourcesDirectory)"
              imageId=$(cat imageid.txt)
              echo "##vso[task.setvariable variable=imageId]$imageId"
              docker tag $imageId $(imageRepository):latest
              echo "Imagename: $(imageRepository):$(tag)"

              docker images
      displayName: Build and Tag Docker Image
      name: BuildImage
    
    - task: Docker@2
      displayName: Login to Docker Hub
      inputs:
       command: login
       containerRegistry: 'KPDockerConnection'
  
    - task: Docker@2
      displayName: Push Docker Image
      inputs:
        command: push
        containerRegistry: 'KPDockerConnection'
        repository: '$(imageRepository)'
        tags: '$(tag)'
      
       
    - task: DockerCompose@0
      displayName: Expose ports & Run Docker Image
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'KPDockerConnection'
        dockerComposeFile: '**/docker-compose.yml'
        ports: 8080:80
        action: 'Run services'
    